import type { EmployeeJobType } from "@prisma/client";
import type { NavItem } from "@/lib/nav-config";

export const CAPABILITIES = {
  TRANSPORT_ROUTES_VIEW: "transport:routes:view",
  TRANSPORT_ROUTES_MANAGE: "transport:routes:manage",
  SECURITY_VISITOR_LOG: "security:visitor:log",
  CLEANER_ZONE_TASKS: "cleaner:zone:tasks",
  SPORTS_SCHEDULE: "sports:schedule",
  LIBRARY_MANAGE: "library:manage",
  FEES_VIEW: "fees:view",
  PAYROLL_VIEW: "payroll:view",
  ATTENDANCE_MARK: "attendance:mark",
  LEAVE_REQUEST: "leave:request",
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

const JOB_TYPE_CAPABILITIES: Record<EmployeeJobType, Capability[]> = {
  TEACHER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK],
  CLASS_TEACHER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK],
  PET_MASTER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK, CAPABILITIES.SPORTS_SCHEDULE],
  LIBRARIAN: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK, CAPABILITIES.LIBRARY_MANAGE],
  LAB_ASSISTANT: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK],
  SPORTS_COACH: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK, CAPABILITIES.SPORTS_SCHEDULE],
  ACCOUNTANT: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.FEES_VIEW],
  OFFICE_CLERK: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST],
  RECEPTIONIST: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.SECURITY_VISITOR_LOG],
  VAN_DRIVER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.TRANSPORT_ROUTES_VIEW, CAPABILITIES.ATTENDANCE_MARK],
  BUS_DRIVER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.TRANSPORT_ROUTES_VIEW, CAPABILITIES.ATTENDANCE_MARK],
  TRANSPORT_COORDINATOR: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.TRANSPORT_ROUTES_VIEW, CAPABILITIES.TRANSPORT_ROUTES_MANAGE],
  SECURITY_GUARD: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.SECURITY_VISITOR_LOG, CAPABILITIES.ATTENDANCE_MARK],
  SECURITY_SUPERVISOR: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.SECURITY_VISITOR_LOG, CAPABILITIES.ATTENDANCE_MARK],
  CLEANER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.CLEANER_ZONE_TASKS, CAPABILITIES.ATTENDANCE_MARK],
  JANITOR: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.CLEANER_ZONE_TASKS, CAPABILITIES.ATTENDANCE_MARK],
  GARDENER: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.CLEANER_ZONE_TASKS, CAPABILITIES.ATTENDANCE_MARK],
  MAINTENANCE_STAFF: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.CLEANER_ZONE_TASKS, CAPABILITIES.ATTENDANCE_MARK],
  CANTEEN_STAFF: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK],
  NURSE: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST, CAPABILITIES.ATTENDANCE_MARK],
  COUNSELLOR: [CAPABILITIES.PAYROLL_VIEW, CAPABILITIES.LEAVE_REQUEST],
  PRINCIPAL: [CAPABILITIES.PAYROLL_VIEW],
  VICE_PRINCIPAL: [CAPABILITIES.PAYROLL_VIEW],
};

export function getCapabilitiesForJobType(jobType: EmployeeJobType): Capability[] {
  return JOB_TYPE_CAPABILITIES[jobType] ?? [CAPABILITIES.PAYROLL_VIEW];
}

export function hasCapability(jobType: EmployeeJobType, capability: Capability): boolean {
  return getCapabilitiesForJobType(jobType).includes(capability);
}

export function getStaffNavForJobType(jobType: EmployeeJobType): NavItem[] {
  const caps = getCapabilitiesForJobType(jobType);
  const nav: NavItem[] = [
    { href: "/staff", label: "Dashboard", icon: "layout-dashboard" },
    { href: "/staff/payroll", label: "My Salary", icon: "credit-card" },
    { href: "/staff/leave", label: "Leave", icon: "file-text" },
  ];

  if (caps.includes(CAPABILITIES.TRANSPORT_ROUTES_VIEW)) {
    nav.push({ href: "/staff/transport", label: "Transport", icon: "calendar" });
  }
  if (caps.includes(CAPABILITIES.SECURITY_VISITOR_LOG)) {
    nav.push({ href: "/staff/security", label: "Visitor Log", icon: "clipboard-check" });
  }
  if (caps.includes(CAPABILITIES.CLEANER_ZONE_TASKS)) {
    nav.push({ href: "/staff/cleaning", label: "Cleaning Tasks", icon: "clipboard-check" });
  }
  if (caps.includes(CAPABILITIES.SPORTS_SCHEDULE)) {
    nav.push({ href: "/staff/sports", label: "Sports", icon: "calendar-days" });
  }
  if (caps.includes(CAPABILITIES.LIBRARY_MANAGE)) {
    nav.push({ href: "/staff/library", label: "Library", icon: "book-open" });
  }
  if (caps.includes(CAPABILITIES.FEES_VIEW)) {
    nav.push({ href: "/staff/fees", label: "Fees Report", icon: "dollar-sign" });
  }
  if (caps.includes(CAPABILITIES.ATTENDANCE_MARK)) {
    nav.push({ href: "/staff/attendance", label: "Attendance", icon: "clock" });
  }

  return nav;
}
